### ISSUE TITLE
Error: node\r: No such file or directory

### ISSUE THREAD

**Issue by nalmeida** [jparkerweb/Bivariate#6]
I have installed the global version on Mac (macOS Sierra v10.12.6). 
I am getting the following error when I try to run ```$ bivariate```

```
$ bivariate
env: node\r: No such file or directory
```

It may be caused by differences of encoding from Win and Mac. Is it the case? Is Bivariate coded on windows?

**Comment by jparkerweb** [comment]
I did develop Birvariate on a Windows machine.  Will need to borrow a freind's macbook to take a look (since I don't have one).

thanks for reporting the error.

**Comment by jparkerweb** [comment]
Doing a little research, it appears it may be a line ending issue.  I will update all line ending to UNIX format in my next commit; Hopefully that will fix the problem.

**Comment by jparkerweb** [comment]
@nalmeida is this still an issue for you?

**Comment by nalmeida** [comment]
Hi @jparkerweb, 

Yes, it still a issue but I have fixed it converting the line breaks to the ```unix``` format. I can make you a pull request in order to you test it on Windows environment and, if it is ok, you can merge it in the project. How does it sound to you?

**Comment by jparkerweb** [comment]
@nalmeida 

That would be great.
Thanks!

**Comment by nalmeida** [comment]
@jparkerweb,

I have unistalled and installed again the npm package globally and, even without changing the line brake to ```unix```, it has worked. So I would consider it fixed. I case it happens again in the future, I have used the [dos2unix](http://dos2unix.sourceforge.net/) lib to fix it using the following command:

```
$ dos2unix app.js
```

Tks for the support.
